### ISSUE TITLE
Getting a "There is no data provider registered that can provide view data." condition when launching the extension

### ISSUE THREAD

**Issue by pcartwright2** [Nagendra080389/salesforce-event-subscriber#13]
I have SF CLI and SFDX installed properly.  I can interact with the Org from VS Code.  The Org browser extension works.  Not sure what I need to do.  See attachment.

![2023-11-16 15_16_22-platformEventSubscriberToast js - PeteDev1 - Visual Studio Code](https://github.com/Nagendra080389/salesforce-event-subscriber/assets/32269293/4530b9a8-73e4-4779-9d64-2fca601a3a8d)

**Comment by Nagendra080389** [comment]
Is this still happening? If yes, can you please share what comes in the output console of "Streaming Subscriber" ?

![image](https://github.com/Nagendra080389/salesforce-event-subscriber/assets/6088582/6e01a4c3-faee-492f-9a7e-51b777c3c79b)

**Comment by Nagendra080389** [comment]
Closing this as there is no further response to this ticket.
